// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddTripToBookmarksController from "./add_trip_to_bookmarks_controller"
application.register("add-trip-to-bookmarks", AddTripToBookmarksController)

import DisableButtonController from "./disable_button_controller"
application.register("disable-button", DisableButtonController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomepageController from "./homepage_controller"
application.register("homepage", HomepageController)

import MapController from "./map_controller"
application.register("map", MapController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
